apiVersion: v1
kind: Service

metadata:
  name: ingestion-service
  namespace: backend
  labels:
    group: ingestion-service

spec:
  type: ClusterIP
  selector:
    group: ingestion-service
  ports:
    - protocol: TCP
      port: 81
      targetPort: 8081