apiVersion: apps/v1
kind: Deployment

metadata:
  name: ingestion-service
  namespace: backend

  labels:
    app: ingestion-service
    group: ingestion-service


spec:
  replicas: 1

  selector:
    matchLabels:
      group: ingestion-service
  template:
    metadata:
      labels: 
        app: ingestion-service
        group: ingestion-service

    spec:
      containers:
        - name: ingestion-service
          image: ingestion-service:latest
          imagePullPolicy: Never
          
          ports:
          - containerPort: 8081
          env:
          - name: ASPNETCORE_URLS
            value: "http://+:8081"
          - name: ConnectionStrings__DefaultConnection
            value: "Host=postgres;Port=5432;Database=default_db;Username=admin;Password=admin;SSL Mode=Disable"
