apiVersion: apps/v1
kind: StatefulSet

metadata:
  name: sensor
  namespace: sensors

spec:
  serviceName: "sensor-headless"
  replicas: 5

  selector:
    matchLabels:
      app: sensor

  template:
    metadata:
      labels:
        app: sensor

    spec:
      containers:
      - name: sensor-container
        image: sensor-simulation:latest
        imagePullPolicy: Never
        
        env:
          - name: GATEWAY_URL
            value: "http://api-gateway.backend.svc.cluster.local:80"
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name