apiVersion: v1
kind: Service

metadata:
  name: notification-service
  namespace: backend
  labels:
    group: notification-service


spec:
  type: ClusterIP
  selector:
    group: notification-service
  
  ports:
    - protocol: TCP
      port: 84
      targetPort: 8084

  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800