services:
  database:
    container_name: snus-db 
    image: "postgres:16-alpine"

    ports: 
      - 5433:5432  
    
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: default_db

    env_file:
      - .env

    volumes:
      - pgdata:/var/lib/postgresql/data/

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d default_db"]
      interval: 5s
      timeout: 5s
      retries: 5


volumes:
  pgdata: